from __future__ import annotations

import os
import subprocess
import time
from contextlib import contextmanager
from pathlib import Path

from bench_cli.config.postgres_config import PostgresConfig
from bench_cli.platform import get_package_manager, is_alpine, is_macos, service_command, service_running, which
from bench_cli.utils import run_command


class PostgresManager:
    """Install and operate PostgreSQL without exposing its details to callers."""

    engine = "postgres"

    def __init__(self, config: PostgresConfig) -> None:
        self.config = config

    @property
    def is_dedicated(self) -> bool:
        return bool(self.config.instance)

    def service_unit(self) -> str:
        return f"postgresql-{self.config.instance}" if self.is_dedicated else "postgresql"

    def data_dir(self) -> str:
        return self.config.data_dir or f"/var/lib/postgresql/{self.config.instance}"

    def instance_socket(self) -> str:
        return self.config.socket_path or f"/run/postgresql/{self.config.instance}"

    def is_installed(self) -> bool:
        # Debian keeps the server binary in a versioned directory, while the
        # client is always on PATH. A shared system service only needs psql;
        # dedicated clusters additionally require postgres/initdb/pg_ctl.
        if not self._binary("psql"):
            return False
        return not self.is_dedicated or bool(self._binary("postgres"))

    @staticmethod
    def _binary(name: str) -> str | None:
        """Find versioned PostgreSQL binaries on Debian as well as PATH."""
        if path := which(name):
            return path
        result = subprocess.run(["pg_config", "--bindir"], capture_output=True, text=True)
        candidate = Path(result.stdout.strip()) / name
        return str(candidate) if result.returncode == 0 and candidate.exists() else None

    def install(self) -> None:
        if self.is_installed():
            return
        package_manager = get_package_manager()
        if is_macos():
            package_manager.install("postgresql")
        elif is_alpine():
            package_manager.install("postgresql", "postgresql-client")
        else:
            package_manager.install("postgresql", "postgresql-client")

    def start(self) -> None:
        if is_macos():
            run_command(["brew", "services", "start", "postgresql"])
        elif self.is_dedicated:
            run_command(["sudo", "-u", "postgres", self._binary("pg_ctl") or "pg_ctl", "-D", self.data_dir(), "-w", "start"])
        else:
            run_command(service_command("start", self.service_unit()))

    def stop(self) -> None:
        if is_macos():
            run_command(["brew", "services", "stop", "postgresql"])
        elif self.is_dedicated:
            run_command(["sudo", "-u", "postgres", self._binary("pg_ctl") or "pg_ctl", "-D", self.data_dir(), "-w", "stop"])
        else:
            run_command(service_command("stop", self.service_unit()))

    def service_is_active(self) -> bool:
        return service_running(self.service_unit()) if not self.is_dedicated else Path(self.data_dir(), "postmaster.pid").exists()

    def provision_instance(self, staging_dir: Path) -> None:
        if not self.is_dedicated:
            raise RuntimeError("provision_instance called for a shared PostgreSQL backend")
        data_dir = self.data_dir()
        socket_dir = self.instance_socket()
        run_command(["sudo", "install", "-d", "-m", "700", "-o", "postgres", "-g", "postgres", data_dir])
        run_command(["sudo", "install", "-d", "-m", "775", "-o", "postgres", "-g", "postgres", socket_dir])
        if not Path(data_dir, "PG_VERSION").exists():
            run_command(["sudo", "-u", "postgres", self._binary("initdb") or "initdb", "-D", data_dir, "--auth-local=peer", "--auth-host=scram-sha-256"])
        self._configure_instance(staging_dir)
        self.start()
        self._configure_admin_role()
        self._wait_until_reachable()

    def _configure_admin_role(self) -> None:
        """Ensure the configured administrative role can authenticate over TCP."""
        password = self.config.root_password.replace("'", "''")
        role = self.config.admin_user.replace('"', '""')
        sql = f'DO $$ BEGIN CREATE ROLE "{role}" WITH LOGIN SUPERUSER PASSWORD \'{password}\'; EXCEPTION WHEN duplicate_object THEN ALTER ROLE "{role}" WITH LOGIN SUPERUSER PASSWORD \'{password}\'; END $$;'
        subprocess.run(
            ["sudo", "-u", "postgres", "psql", "-d", "postgres", "-c", sql],
            check=True,
            capture_output=True,
            text=True,
        )

    def _configure_instance(self, staging_dir: Path) -> None:
        content = "\n".join((
            "# Generated by bench; do not edit.",
            f"port = {self.config.port}",
            f"unix_socket_directories = '{self.instance_socket()}'",
            "listen_addresses = '127.0.0.1'",
            "",
        ))
        staged = staging_dir / "postgresql.conf"
        staged.write_text(content)
        run_command(["sudo", "cp", str(staged), f"{self.data_dir()}/postgresql.conf"])

    def check_credentials(self, password: str | None = None) -> bool:
        env = {**os.environ, "PGPASSWORD": self.config.root_password if password is None else password}
        cmd = [self._binary("psql") or "psql", "-U", self.config.admin_user, "-d", "postgres", "-tAc", "SELECT 1"]
        if self.config.socket_path:
            cmd += ["-h", self.config.socket_path]
        else:
            cmd += ["-h", self.config.host, "-p", str(self.config.port)]
        return subprocess.run(cmd, env=env, capture_output=True, text=True).returncode == 0

    def _wait_until_reachable(self, timeout: float = 30.0) -> None:
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if self.check_credentials():
                return
            time.sleep(0.5)

    def kill_process(self, process_id: int) -> None:
        env = {**os.environ, "PGPASSWORD": self.config.root_password}
        subprocess.run(
            ["psql", "-U", self.config.admin_user, "-d", "postgres", "-h", self.config.socket_path or self.config.host,
             "-p", str(self.config.port), "-c", "SELECT pg_terminate_backend(" + str(int(process_id)) + ")"],
            env=env,
            check=True,
            capture_output=True,
            text=True,
        )

    @contextmanager
    def snapshot_lock(self):
        """Force a checkpoint before a filesystem snapshot.

        PostgreSQL cannot safely use MariaDB's table lock. A checkpoint makes
        the cluster crash-recoverable; restore still starts the database before
        accepting application traffic.
        """
        env = {**os.environ, "PGPASSWORD": self.config.root_password}
        cmd = ["psql", "-U", self.config.admin_user, "-d", "postgres", "-c", "CHECKPOINT"]
        cmd += ["-h", self.config.socket_path or self.config.host, "-p", str(self.config.port)]
        subprocess.run(cmd, env=env, check=True, capture_output=True, text=True)
        yield
