from __future__ import annotations

import getpass
import subprocess
from pathlib import Path
from typing import override

from pilot.managers.admin_env_manager import AdminEnvManager
from pilot.managers.process_manager import ProcessDefinition, _cli_root
from pilot.managers.process_managers.base import ManagedProcessManager, UnitGroup, ServiceRenderer
from pilot.platform import (
    _privileged,
    service_command,
    service_disable_command,
    service_enable_command,
    service_running,
    which,
)
from pilot.utils import run_command


class OpenRCRenderer(ServiceRenderer):
    """Builds a supervise-daemon openrc-run init script for a bench process."""

    def __init__(self, bench_name: str, user: str) -> None:
        super().__init__(bench_name)
        self.user = user

    @override
    def render(self, pd: ProcessDefinition) -> str:
        service_name = f"{self.bench_name}-{pd.name}"
        command, _, command_args = pd.command.partition(" ")
        # supervise-daemon requires an absolute path; resolve bare commands.
        if not command.startswith("/"):
            command = which(command) or command

        env = "".join(f'export {k}="{v}"\n' for k, v in pd.env.items())
        directory = f'directory="{pd.working_dir}"\n' if pd.working_dir else ""
        args = f'command_args="{command_args}"\n' if command_args else ""
        return (
            f"#!/sbin/openrc-run\n"
            f"# {service_name} - generated by bench, do not edit\n"
            f'description="{service_name}"\n'
            f"supervisor=supervise-daemon\n"
            f'command_user="{self.user}"\n'
            f"{env}"
            f"{directory}"
            f'command="{command}"\n'
            f"{args}"
            f'pidfile="/run/{service_name}.pid"\n'
            f'output_log="{pd.log_file}"\n'
            f'error_log="{pd.log_file}.error.log"\n'
            f"respawn_delay=5\n\n"
            f"depend() {{\n"
            f"\tafter net firewall mariadb\n"
            f"}}\n"
        )


class OpenRCProcessManager(ManagedProcessManager):
    """Manages bench processes via OpenRC (production on Alpine).

    One supervise-daemon init script per process under config/openrc/, symlinked
    into /etc/init.d/. No socket activation; the admin runs as a plain supervised
    process on admin.port with nginx proxying straight to it.
    """

    @property
    def openrc_conf_dir(self) -> Path:
        return self.bench.config_path / "openrc"

    @property
    def init_d_dir(self) -> Path:
        return Path("/etc/init.d")

    @override
    def write_config(self) -> None:
        AdminEnvManager(_cli_root()).ensure()
        self._ensure_redis_config()
        self._ensure_gunicorn_config()
        self.openrc_conf_dir.mkdir(parents=True, exist_ok=True)
        defs = self._prod_process_definitions()
        wanted = {self._service_name(pd.name) for pd in defs}
        for path in self.openrc_conf_dir.iterdir():
            if path.is_file() and path.name not in wanted:
                path.unlink()
        renderer = OpenRCRenderer(self.bench.config.name, getpass.getuser())
        for pd in defs:
            script = self.openrc_conf_dir / self._service_name(pd.name)
            script.write_text(renderer.render(pd))
            script.chmod(0o755)

    @override
    def install_config(self) -> None:
        self.openrc_conf_dir.mkdir(parents=True, exist_ok=True)
        for pd in self._prod_process_definitions():
            service = self._service_name(pd.name)
            src = (self.openrc_conf_dir / service).resolve()
            dst = self.init_d_dir / service
            run_command(_privileged(["ln", "-sf", str(src), str(dst)]))
            run_command(service_enable_command(service))

    @override
    def reload_manager_config(self) -> None:
        pass  # OpenRC re-reads scripts on next start; no daemon-reload needed.

    @override
    def ensure_ready(self) -> None:
        self.install_config()

    @override
    def apply_unit_action(self, action: str, role: UnitGroup) -> None:
        for service in self._services(role):
            run_command(service_command(action, service))

    @override
    def are_units_running(self, role: UnitGroup) -> bool:
        return any(service_running(s) for s in self._services(role))

    def is_configured(self) -> bool:
        return (self.init_d_dir / self._service_name("web")).exists()

    def remove_services(self) -> None:
        """Stop, disable and unlink every service this bench owns (best-effort)."""
        for service in self._services(UnitGroup.ADMIN) + self._services(UnitGroup.WORKLOAD):
            subprocess.run(service_command("stop", service), capture_output=True)
            subprocess.run(service_disable_command(service), capture_output=True)
            dst = self.init_d_dir / service
            if dst.is_symlink() or dst.exists():
                subprocess.run(_privileged(["rm", "-f", str(dst)]), capture_output=True)

    def _service_name(self, process_name: str) -> str:
        return f"{self.bench.config.name}-{process_name}"

    def _services(self, role: UnitGroup) -> list[str]:
        if role is UnitGroup.WEB:
            return [self._service_name("web")]
        defs = self._prod_process_definitions()
        if role is UnitGroup.ADMIN:
            defs = [pd for pd in defs if pd.name == "admin"]
        else:
            defs = [pd for pd in defs if pd.name != "admin"]
        return [self._service_name(pd.name) for pd in defs]
