/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    Apps: typeof import('./src/components/sites/Apps.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Backups: typeof import('./src/components/sites/Backups.vue')['default']
    Config: typeof import('./src/components/sites/Config.vue')['default']
    MarketplaceAppCard: typeof import('./src/components/MarketplaceAppCard.vue')['default']
    NewSiteDialog: typeof import('./src/components/NewSiteDialog.vue')['default']
    ReconnectOverlay: typeof import('./src/components/ReconnectOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskStream: typeof import('./src/components/TaskStream.vue')['default']
    TerminalOutput: typeof import('./src/components/TerminalOutput.vue')['default']
    UpdatesAvailableButton: typeof import('./src/components/UpdatesAvailableButton.vue')['default']
  }
}
