/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./src/components/ActionMenu.vue')['default']
    Actions: typeof import('./src/components/sites/settings/Actions.vue')['default']
    AddAppFromGithubDialog: typeof import('./src/components/AddAppFromGithubDialog.vue')['default']
    AddDomainDialog: typeof import('./src/components/sites/settings/domains/AddDomainDialog.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    Apps: typeof import('./src/components/sites/Apps.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Backups: typeof import('./src/components/sites/Backups.vue')['default']
    BenchSwitcherDialog: typeof import('./src/components/BenchSwitcherDialog.vue')['default']
    ChartCard: typeof import('./src/components/ChartCard.vue')['default']
    ChooseSiteDialog: typeof import('./src/components/ChooseSiteDialog.vue')['default']
    Config: typeof import('./src/components/sites/Config.vue')['default']
    CronScheduleControl: typeof import('./src/components/CronScheduleControl.vue')['default']
    Danger: typeof import('./src/components/sites/settings/Danger.vue')['default']
    Domains: typeof import('./src/components/sites/settings/Domains.vue')['default']
    Firewall: typeof import('./src/components/settings/Firewall.vue')['default']
    General: typeof import('./src/components/sites/settings/General.vue')['default']
    Git: typeof import('./src/components/settings/Git.vue')['default']
    InstallAppDialog: typeof import('./src/components/InstallAppDialog.vue')['default']
    LogView: typeof import('./src/components/LogView.vue')['default']
    MarketplaceAppCard: typeof import('./src/components/MarketplaceAppCard.vue')['default']
    NewBenchDialog: typeof import('./src/components/NewBenchDialog.vue')['default']
    NewSiteDialog: typeof import('./src/components/NewSiteDialog.vue')['default']
    ReconnectOverlay: typeof import('./src/components/ReconnectOverlay.vue')['default']
    RemoveDomainDialog: typeof import('./src/components/sites/settings/domains/RemoveDomainDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S3: typeof import('./src/components/settings/S3.vue')['default']
    Settings: typeof import('./src/components/sites/Settings.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SimpleTable: typeof import('./src/components/SimpleTable.vue')['default']
    Snapshots: typeof import('./src/components/settings/Snapshots.vue')['default']
    SystemInfo: typeof import('./src/components/settings/SystemInfo.vue')['default']
    TaskStep: typeof import('./src/components/TaskStep.vue')['default']
    TaskSteps: typeof import('./src/components/TaskSteps.vue')['default']
    TaskStream: typeof import('./src/components/TaskStream.vue')['default']
    TerminalOutput: typeof import('./src/components/TerminalOutput.vue')['default']
    UpdateAppsDialog: typeof import('./src/components/UpdateAppsDialog.vue')['default']
    UpdatesAvailableButton: typeof import('./src/components/UpdatesAvailableButton.vue')['default']
    Workers: typeof import('./src/components/settings/Workers.vue')['default']
  }
}
