/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./src/components/common/ActionMenu.vue')['default']
    Actions: typeof import('./src/components/sites/settings/Actions.vue')['default']
    AddAppFromGithubDialog: typeof import('./src/components/apps/AddAppFromGithubDialog.vue')['default']
    AddDomainDialog: typeof import('./src/components/sites/settings/domains/AddDomainDialog.vue')['default']
    AppIcon: typeof import('./src/components/apps/AppIcon.vue')['default']
    Apps: typeof import('./src/components/sites/Apps.vue')['default']
    AppSidebar: typeof import('./src/components/common/AppSidebar.vue')['default']
    BackupConfigDialog: typeof import('./src/components/sites/BackupConfigDialog.vue')['default']
    Backups: typeof import('./src/components/sites/Backups.vue')['default']
    BenchSwitcherDialog: typeof import('./src/components/benches/BenchSwitcherDialog.vue')['default']
    ChartCard: typeof import('./src/components/common/ChartCard.vue')['default']
    ChooseSiteDialog: typeof import('./src/components/sites/ChooseSiteDialog.vue')['default']
    Config: typeof import('./src/components/sites/Config.vue')['default']
    CronScheduleControl: typeof import('./src/components/common/CronScheduleControl.vue')['default']
    Danger: typeof import('./src/components/sites/settings/Danger.vue')['default']
    Domains: typeof import('./src/components/sites/settings/Domains.vue')['default']
    Firewall: typeof import('./src/components/settings/Firewall.vue')['default']
    General: typeof import('./src/components/sites/settings/General.vue')['default']
    Git: typeof import('./src/components/settings/Git.vue')['default']
    GithubMark: typeof import('./src/components/icons/GithubMark.vue')['default']
    InstallAppDialog: typeof import('./src/components/apps/InstallAppDialog.vue')['default']
    LogView: typeof import('./src/components/logs/LogView.vue')['default']
    MarketplaceAppCard: typeof import('./src/components/marketplace/MarketplaceAppCard.vue')['default']
    MarketplaceFilters: typeof import('./src/components/marketplace/MarketplaceFilters.vue')['default']
    MigrationStateBadge: typeof import('./src/components/migrations/MigrationStateBadge.vue')['default']
    MigrationStatusButton: typeof import('./src/components/common/MigrationStatusButton.vue')['default']
    Monitoring: typeof import('./src/components/sites/Monitoring.vue')['default']
    NewBenchDialog: typeof import('./src/components/benches/NewBenchDialog.vue')['default']
    NewSiteDialog: typeof import('./src/components/sites/NewSiteDialog.vue')['default']
    PasswordStrengthMeter: typeof import('./src/components/common/PasswordStrengthMeter.vue')['default']
    PilotLogo: typeof import('./src/components/common/PilotLogo.vue')['default']
    ReconnectOverlay: typeof import('./src/components/common/ReconnectOverlay.vue')['default']
    RemoveDomainDialog: typeof import('./src/components/sites/settings/domains/RemoveDomainDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S3Bucket: typeof import('./src/components/settings/S3Bucket.vue')['default']
    Settings: typeof import('./src/components/sites/Settings.vue')['default']
    SettingsDialog: typeof import('./src/components/settings/SettingsDialog.vue')['default']
    SimpleTable: typeof import('./src/components/common/SimpleTable.vue')['default']
    SQLCodeEditor: typeof import('./src/components/database/SQLCodeEditor.vue')['default']
    SQLSchemaDialog: typeof import('./src/components/database/SQLSchemaDialog.vue')['default']
    SshKeys: typeof import('./src/components/settings/SshKeys.vue')['default']
    SystemInfo: typeof import('./src/components/settings/SystemInfo.vue')['default']
    TaskStep: typeof import('./src/components/tasks/TaskStep.vue')['default']
    TaskSteps: typeof import('./src/components/tasks/TaskSteps.vue')['default']
    TaskStream: typeof import('./src/components/tasks/TaskStream.vue')['default']
    TerminalOutput: typeof import('./src/components/common/TerminalOutput.vue')['default']
    UpdateAppsDialog: typeof import('./src/components/apps/UpdateAppsDialog.vue')['default']
    Uptime: typeof import('./src/components/sites/Uptime.vue')['default']
    Waf: typeof import('./src/components/settings/Waf.vue')['default']
    WafAnalytics: typeof import('./src/components/common/WafAnalytics.vue')['default']
    WafCustomRules: typeof import('./src/components/settings/WafCustomRules.vue')['default']
    Workers: typeof import('./src/components/settings/Workers.vue')['default']
  }
}
